version: '3.8'

services:
  dev:
    build:
      context: .
      target: dev
    image: qauth:dev
    container_name: qauth-dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
    command: npm run dev

  build:
    image: qauth:dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run build

  test-unit:
    image: qauth:dev
    volumes:
      - .:/app
      - /app/node_modules
      - coverage:/app/coverage
    environment:
      - NODE_ENV=test
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run test:unit

  test-integration:
    image: qauth:dev
    volumes:
      - .:/app
      - /app/node_modules
      - coverage:/app/coverage
    environment:
      - NODE_ENV=test
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run test:integration

  test-e2e:
    image: qauth:dev
    ipc: host
    volumes:
      - .:/app
      - /app/node_modules
      - /app/playwright-report
      - /app/test-results
    environment:
      - NODE_ENV=test
      - NEXT_TELEMETRY_DISABLED=1
      - CI=true
    command: npm run test:e2e

  test-e2e-ui:
    image: qauth:dev
    ipc: host
    volumes:
      - .:/app
      - /app/node_modules
      - /app/playwright-report
      - /app/test-results
    environment:
      - NODE_ENV=test
      - NEXT_TELEMETRY_DISABLED=1
      - CI=true
    command: npm run test:e2e:ui

  test-e2e-debug:
    image: qauth:dev
    ipc: host
    volumes:
      - .:/app
      - /app/node_modules
      - /app/playwright-report
      - /app/test-results
    environment:
      - NODE_ENV=test
      - NEXT_TELEMETRY_DISABLED=1
      - CI=true
      - PWDEBUG=1
    command: npm run test:e2e:debug

  test-perf:
    image: qauth:dev
    ipc: host
    volumes:
      - .:/app
      - /app/node_modules
      - /app/playwright-report
      - /app/test-results
    environment:
      - NODE_ENV=test
      - NEXT_TELEMETRY_DISABLED=1
      - CI=true
    command: npm run test:perf

  test-watch:
    image: qauth:dev
    volumes:
      - .:/app
      - /app/node_modules
      - coverage:/app/coverage
    environment:
      - NODE_ENV=test
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run test:watch

  test-coverage:
    image: qauth:dev
    volumes:
      - .:/app
      - /app/node_modules
      - coverage:/app/tests/coverage
    environment:
      - NODE_ENV=test
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run test:coverage

  test-all:
    image: qauth:dev
    ipc: host
    volumes:
      - .:/app
      - /app/node_modules
      - coverage:/app/coverage
      - /app/playwright-report
      - /app/test-results
    environment:
      - NODE_ENV=test
      - NEXT_TELEMETRY_DISABLED=1
      - CI=true
    command: npm run test:all

volumes:
  coverage:

networks:
  default:
    name: qauth-dev-network
    driver: bridge
